# -------------------------------------------------------------------
# Giec Database Settings
# -------------------------------------------------------------------
#
#
#   Author : PLIQUE Guillaume
#   Organization : Medialab - Sciences Po
#   Version : 1.0

host: YOUR_HOST
user: YOUR_USER
password: YOUR_PASSWORD
database: YOUR_DATABASE