# -------------------------------------------------------------------
# Giec Database Settings
# -------------------------------------------------------------------
#
#
#   Author : PLIQUE Guillaume
#   Organization : Medialab - Sciences Po
#   Version : 1.0

host: localhost
port: 3306
user: root
password: YOUR_PASSWORD
database: giec